### ISSUE TITLE
Line 16: comment refers to code on line 530 but line 530 is a comment!

### ISSUE THREAD

**Issue by ahope1** [codingbychanche/BoolsLostBit#1]
https://github.com/codingbychanche/BoolsLostBit/blob/3e6d8965b36a9dcd67aeab234cdb5c5f71ddf95d/Game.sh#L16

**Comment by codingbychanche** [comment]
Thank you! The Comedy in line 16 refers to the wrong line if code. The right reference is line 540.

**Comment by codingbychanche** [comment]
... Comment, nor Comedy...

**Comment by codingbychanche** [comment]
Fixed! comments are good but have a tendency to erode. The right reference is: Line 540.

Thank you! Drop me a line, if you enjoyed the game ;-)
